//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Data.Model
{
    using System;
    
    public partial class GetDataOnDateAndSearchKey_Result1
    {
        public int MasterID { get; set; }
        public string LoginName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string BusinessStreet { get; set; }
        public string BusinessStreet2 { get; set; }
        public string BusinessStreet3 { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string BusinessPostalCode { get; set; }
        public string BusinessCountry { get; set; }
        public string HomeStreet { get; set; }
        public string HomeStreet2 { get; set; }
        public string HomeStreet3 { get; set; }
        public string HomeCity { get; set; }
        public string HomeState { get; set; }
        public string HomePostalCode { get; set; }
        public string HomeCountry { get; set; }
        public string OtherStreet { get; set; }
        public string OtherStreet2 { get; set; }
        public string OtherStreet3 { get; set; }
        public string OtherCity { get; set; }
        public string OtherState { get; set; }
        public string OtherPostalCode { get; set; }
        public string OtherCountry { get; set; }
        public string AssistantPhone { get; set; }
        public string BusinessFax { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessPhone2 { get; set; }
        public string CallBack { get; set; }
        public string CarPhone { get; set; }
        public string CompanyMainPhone { get; set; }
        public string HomeFax { get; set; }
        public string HomePhone { get; set; }
        public string HomePhone2 { get; set; }
        public string ISDN { get; set; }
        public string MobilePhone { get; set; }
        public string OtherFax { get; set; }
        public string OtherPhone { get; set; }
        public string Pager { get; set; }
        public string PrimaryPhone { get; set; }
        public string RadioPhone { get; set; }
        public string TTYTTDPhone { get; set; }
        public string Telex { get; set; }
        public string AssistantName { get; set; }
        public string BirthDate { get; set; }
        public string ManagerName { get; set; }
        public string Notes { get; set; }
        public string OtherAddressPOBox { get; set; }
        public string Spouse { get; set; }
        public string Webpage { get; set; }
        public string PersonalWebpage { get; set; }
        public string ImportedSource { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Url { get; set; }
        public string Location { get; set; }
        public string CurrentJob { get; set; }
        public Nullable<System.DateTime> Posted { get; set; }
        public string SearchString { get; set; }
        public string LinkedInStatus { get; set; }
        public string LinkedInIndustryType { get; set; }
        public Nullable<bool> IsSentToAccountMgr { get; set; }
        public string url2 { get; set; }
        public string url3 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public Nullable<System.DateTime> SearchedDate { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<System.DateTime> sentToprocessFileDate { get; set; }
        public Nullable<System.DateTime> sentToAcMgrFileDate { get; set; }
        public Nullable<int> statusid { get; set; }
        public string comment { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
